### ISSUE TITLE
This container is not updating with new releases of nxfilter

### ISSUE THREAD

**Issue by dgibbs64** [packetworks/docker-nxfilter#13]
Since there is no automation currently setup a new build is not yet being automatically triggered.

My suggestion is using travis-ci to check the nxfilter changelog http://www.nxfilter.org/changelog/nxfilter.txt if is has changed push the file to this repo and that will trigger a new build.

This repo does a similar thing and may help
https://github.com/dgibbs64/SteamCMD-AppID-List

**Comment by cron410** [comment]
I've heard of TravisCI but not familiar with how it works. Do I need to run something on a server or is it a public service?

**Comment by dgibbs64** [comment]
It's free and you don't need to host anything. You can setup a daily task to run a script to check for an update. I have a repo that checks for steamcmd appid updated. Check out my steamcmd repos for an example

**Comment by vbap** [comment]
Hi,

Any updates on this? The docker is at 4.3.6.4 whereas nx is at 4.3.7.2

Thanks

**Comment by cron410** [comment]
I just manually triggered the build until I figure out travis-ci. Better automation here is definitely on my priority for this repo, I just haven't had much time this summer.

**Comment by dgibbs64** [comment]
I'm actually looking at GitHub actions to do the same job as travis now as it's already built in to GitHub. Also found its faster.

**Comment by dgibbs64** [comment]
I would do this myself as well but I haven't had time yet

**Comment by joaoherberto** [comment]
So how does one actually update the docker image? Sorry, newbie...

**Comment by cron410** [comment]
You can use a Watchtower container to Auto-update your containers, or
follow this article which explains more thoroughly, the manual process.
https://ma.ttias.be/update-docker-container-latest-version/

**Comment by marafa** [comment]
you need a `.travis.yml` file in the root directory of your repo

tutorial is [here](https://docs.travis-ci.com/user/tutorial/)

personally in my cloned repo i have a build script with just
```
git pull && podman build -t packetworks/nxfilter -f Dockerfile .
```
which is more than sufficient for my needs

**Comment by cron410** [comment]
Just to update you guys, the automated builds using the Docker Hub build system have been running smoothly and are still being triggered by an external service since that was fixed in June or July. My next steps are to remove that external service from the automation workflow and replace it with something simpler and more robust, more details below.

Over the last month I have been working on getting Github Actions set up to do a Multi-Arch build for Raspberry Pi and other ARM platforms and that branch is currently undergoing rapid development (compared to my normal pace). I don't plan on doing much support for the Pi specifically as it is not a recommended platform for mission critical services but I do want to support multiple architectures to accommodate as many use cases as possible. x86 is also on my to-do list for the 32-bit greybeards.

As a result of that progress, I'm currently working on consolidating and simplifying all automation in this repo to Github Actions to make things more transparent to users. This will move all status messages for the entire process to the Github repo and give myself and users a single place to look for issues and health of the build. This includes the version change triggering of automated builds. My goal is to make this container as versatile and stable as possible while minimizing human intervention of the build process.

**Comment by cron410** [comment]
Small update:

I've made a LOT of progress with Github Actions which is good because my cobbled together wget/curl/grep/xargs one-liner is showing it's age and broke the build last night. We are now getting good builds on the `:pi-experimental` tag and will require some more testing and verification before being pushed to `:latest`

Thanks for your patience everyone.

**Comment by cron410** [comment]
Github actions has been completely automated and tested. From now on, a version check is made every day between 1-2pm UTC with a new image being built when the automation finds a new version of NxFilter. 

Next on my roadmap is CI/CD with plenty of testing before a new build gets pushed to the Docker Hub repo. Thank you everyone for your help and patience. It has been a rewarding experience to get NxFilter to this point.
