### ISSUE TITLE
SSLSplit

### ISSUE THREAD

**Issue by r-souza** [packetworks/docker-nxfilter#16]
Hello,

I would like to know why line 21 exists in the Dockerfile.

Line 21:

`COPY --from = vimagick / sslsplit / /`

As described on the [docker hub page](https://hub.docker.com/r/vimagick/sslsplit), "SSLsplit is a tool for intermediate attacks against SSL / TLS encrypted network connections."

This may be legitimate and I am not accusing anyone, but I would like to understand it better.

Thank you for your attention

**Comment by cron410** [comment]
Some users requested this package over on a Google Groups [thread](https://groups.google.com/forum/#!topic/nxfilter200/zR5F9521wPk) for Nxfilter. There's also a great explanation [here](https://www.reddit.com/r/nxfilter/comments/ayh81c/nxfilter_sslsplit_rpm/). It's not used unless you set it up. Instead of maintainting the packaging of SSLSplit for this Alpine based image, I just copy from the vimagick image. I also found another CentOS based docker image here: https://github.com/turboaaa/docker-nxfilter today which was a nice surprise. Always good to see someone doing things a different way. turboaaa seems to also have plans to include SSLSplit for edge cases.

Sidenote: This may be the fastest I've ever responded to a Github notification. You got me at just the right time today.

**Comment by r-souza** [comment]
Now it's very clear to me!

Thanks for answering me so fast!
